// const API_URL_CONSTANTS = {
//   CREATEROLE_API_URL: "api/createRole",
//   CREATE_EMP_API_URL: "api/createEmp",
//   GET_EMPLIST_API_URL: "api/getAllEmps",
//   GET_EMP_API_URL: "api/getEmp",
//   UPDATE_EMP_API_URL: "api/updateEmp",
//   UPDATE_ROLE_API_URL: "api/updateRole",
//   GET_ROLESLIST_API_URL: "api/getAllRole",
//   ROLE_VALIDATE_API_URL: "api/roleValidation",
//   EMAIL_VALIDATE_API_URL: "api/emailValidation",
//   SIGN_IN_API_URL: "api/signin",
//   FORGET_API_URL: "api/forgot",
//   OTP_API_URL: "api/otpValidation",
//   RESET_PASSWORD_API_URL: "api/reset",
//   GET_PROFILE_API_URL: "api/getProfile",
//   UPDATE_PROFILE_API_URL: "api/updateProfile",
//   GET_CUSTOMERS_APP_URL: "api/getAllCustomers",
//   GET_CUSTOMER_INFO_API_URL: "api/getCustomer",
//   CREATE_LEAD_API_URL: "api/createLead",
//   GET_LEADS_API_URL: "api/getAllLeads",
//   GET_LEAD_API_URL: "api/getLead",
//   LEAD_EMAIL_VALIDATE_API_URL: "api/emilValidation",
//   UPDATE_LEAD_API_URL: "api/updateLead",
//   POST_HUB_API_URL: "api/createHub",
//   GET_HUB_API_URL: "api/getAllHubs",
//   GET_HUBORDERS_API_URL: "api/getOrdersByHub",
//   GET_HUBEMP_API_URL: "api/getEmpByHub",
//   GET_HUBSTOCK_API_URL: "api/getStockByHub",
//   GET_HUBSDETAILS_API_URL: "api/getHubsMasterData",
//   CREATE_PRODUCT_API_URL: "api/createProduct",
//   GET_ALLPRODUCTS_API_URL: "api/getProducts",
//   GET_PRODUCT_API_URL: "api/getProduct",
//   GET_PRODUCT_lIST_API_URL: "api/getProducts/Published?sortOrder=Recent",
//   UPDATE_PRODUCT_API_URL: "api/updateProduct",
//   POST_CREATE_INVENTORY_STOCK: "api/createStock",
//   GET_INVENTORY_STOCK: "api/getStock",
//   GET_STOCK_PRODUCT_ID: "api/getStockProductId",
//   GET_STOCK_BY_ID: "api/getStockById",
//   GET_ORDER_REQUEST: "api/getOrder",
//   GET_OREDER_REQUESTS: "orderRequest/api/orderRequests",
//   CREATE_ORDER_REQUEST: "orderRequest/api/createOrderRequest",
//   UPDATE_ORDER_REQUEST: "orderRequest/api/updateOrder",
//   DASHBOARD_ORDER_REQUEST: "api/dashboardOrders",
//   CATEGORIES_MATER_INFO_API_URL: "api/categories",
//   PRODUCT_CATEGORIES_INFO_API_URL: "api/subCategories",
//   BRANDS_INFO_API_URL: "api/brands",
//   PRODUCT_NAMES_INFO_API_URL: "api/getProductsMaster",
//   USER_REQUESTS_API_URL: "userRequest/api/getUserRequests",
//   USER_REQUESTS_INFO_API_URL: "userRequest/api/details",
//   USER_ORDER_REQUESTS_INFO_API_URL: "orderRequest/api/details",
//   UPDATE_USER_REQ_API_URL: "userRequest/api/updateRequest",
//   UPDATE_USER_ORDER_REQ_API_URL: "orderRequest/api/updateRequest",

//   // getVendors
//   GET_VENDORS: "api/getVendors",
//   CREATE_VENDORS: "api/createVendor",
//   UPDATE_VENDORS: "api/updateVendor",

//   GET_CUSTOMERS_INVENTORY_APP_URL: "api/Inventory",
//   GET_CUSTOMERS_INVENTORY_LIST: "api/admin/Inventory",
//   GET_CUSTOMERS_INVENTORY_DETAILS_APP_URL: "api/user/getInventoryDetails",
// };

// export default API_URL_CONSTANTS;

const API_URL_CONSTANTS = {
  CREATEROLE_API_URL: "api/createRole",
  CREATE_EMP_API_URL: "api/createEmp",
  GET_EMPLIST_API_URL: "api/getAllEmps",
  GET_EMP_API_URL: "api/getEmp",
  UPDATE_EMP_API_URL: "api/updateEmp",
  UPDATE_ROLE_API_URL: "api/updateRole",
  GET_ROLESLIST_API_URL: "api/getAllRole",
  ROLE_VALIDATE_API_URL: "api/roleValidation",
  EMAIL_VALIDATE_API_URL: "api/emailValidation",
  SIGN_IN_API_URL: "api/signin",
  FORGET_API_URL: "api/forgot",
  OTP_API_URL: "api/otpValidation",
  RESET_PASSWORD_API_URL: "api/reset",
  GET_PROFILE_API_URL: "api/getProfile",
  UPDATE_PROFILE_API_URL: "api/updateProfile",
  GET_CUSTOMERS_APP_URL: "api/getAllCustomers",
  GET_CUSTOMER_INFO_API_URL: "api/getCustomer",
  CREATE_LEAD_API_URL: "api/createLead",
  GET_LEADS_API_URL: "api/getAllLeads",
  GET_LEAD_API_URL: "api/getLead",
  LEAD_EMAIL_VALIDATE_API_URL: "api/emilValidation",
  UPDATE_LEAD_API_URL: "api/updateLead",
  POST_HUB_API_URL: "api/createHub",
  GET_HUB_API_URL: "api/getAllHubs",
  GET_HUBORDERS_API_URL: "api/getOrdersByHub",
  GET_HUBEMP_API_URL: "api/getEmpByHub",
  GET_HUBSTOCK_API_URL: "api/getStockByHub",
  GET_HUBSDETAILS_API_URL: "api/getHubsMasterData",
  CREATE_PRODUCT_API_URL: "api/createProduct",
  GET_ALLPRODUCTS_API_URL: "api/getProducts",
  GET_PRODUCTS_BY_VENDOR_ID: "api/getProductsByVendorId",
  GET_PRODUCT_API_URL: "api/getProduct",
  GET_PRODUCT_lIST_API_URL: "api/getProducts/Published?sortOrder=Recent",
  UPDATE_PRODUCT_API_URL: "api/updateProduct",
  POST_CREATE_INVENTORY_STOCK: "api/createStock",
  GET_INVENTORY_STOCK: "api/getStock",
  GET_STOCK_PRODUCT_ID: "api/getStockProductId",
  GET_STOCK_BY_ID: "api/getStockById",
  GET_ORDER_REQUEST: "api/getOrder",
  GET_OREDER_REQUESTS: "orderRequest/api/orderRequests",
  CREATE_ORDER_REQUEST: "orderRequest/api/createOrderRequest",
  UPDATE_ORDER_REQUEST: "orderRequest/api/updateOrder",
  DASHBOARD_ORDER_REQUEST: "api/dashboardOrders",
  // added here
  // GET_OREDER_REQUESTS: "api/orderRequests",
  // CREATE_ORDER_REQUEST: "api/createOrderRequest",
  // UPDATE_ORDER_REQUEST: "api/updateOrder",
  // DASHBOARD_ORDER_REQUEST: "api/dashboardOrders",
  // added here
  CATEGORIES_MATER_INFO_API_URL: "api/categories",
  PRODUCT_CATEGORIES_INFO_API_URL: "api/subCategories",
  BRANDS_INFO_API_URL: "api/brands",
  PRODUCT_NAMES_INFO_API_URL: "api/getProductsMaster",
  USER_REQUESTS_API_URL: "userRequest/api/getUserRequests",
  USER_REQUESTS_INFO_API_URL: "userRequest/api/details",
  USER_ORDER_REQUESTS_INFO_API_URL: "orderRequest/api/details",
  UPDATE_USER_REQ_API_URL: "userRequest/api/updateRequest",
  UPDATE_USER_ORDER_REQ_API_URL: "orderRequest/api/updateRequest",

  // getVendors
  GET_VENDORS: "api/getVendors",
  CREATE_VENDORS: "api/createVendor",
  UPDATE_VENDORS: "api/updateVendor",

  GET_CUSTOMERS_INVENTORY_APP_URL: "api/Inventory",
  GET_CUSTOMERS_INVENTORY_LIST: "api/admin/Inventory",
  GET_CUSTOMERS_INVENTORY_DETAILS_APP_URL: "api/user/getInventoryDetails",

  // purchased Products
  GET_PURCHASE_ORDERS: "api/getPurchaseOrders",
  CREATE_PURCHASE_ORDER: "api/createPurchaseOrder", 

  //GRN
  CREATE_GRN:"api/createGRN",
  GET_GRN_BY_POID:"api/getGRNByPoId",
  UPDATE_GRN:"api/updateGRN",

  // PAYMENTS 
  GET_PAYMENT_BY_ID:"api/getPayment", 
  GET_ALL_PAYMENTS_LIST_BY_TENANT_ID:"api/getPayments", 
  UPDATE_PAYMENT_BY_ID:"api/updatePayment",

  
 // MaterialRequest 
 GET_ALL_REQUEST_BY_TENANT_ID:"api/getAllRequests", 
 GET_MATERIAL_RD_BY_ID:"api/getMaterialReuestDetails", 
 UPDATE_MR_BY_ID:"api/updateMaterialReuest",
 CREATE_MATERIAL_REQUEST:"api/createMaterialRequest",
 GET_MREQUEST_PENDING:"api/getAllRequests/pendingStatus",


//  api/getProductsMaster/category
GET_PRODUCTS_BY_CATEGORYID:"api/getProductsMaster/category"
};

export default API_URL_CONSTANTS;
